"""Add recurrence fields to Task

Revision ID: 0a6e0aa7eff3
Revises: 
Create Date: 2025-10-26 14:55:20.053624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6e0aa7eff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_freq', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('repeat_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('repeat_byweekday', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('repeat_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('repeat_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('repeat_count')
        batch_op.drop_column('repeat_until')
        batch_op.drop_column('repeat_byweekday')
        batch_op.drop_column('repeat_interval')
        batch_op.drop_column('repeat_freq')

    op.drop_table('sheet_mapping')
    # ### end Alembic commands ###
